#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# RavenFabric rpi5 Setup Script
# ──────────────────────────────────────────────────────────────────────────────
# Run this on a Raspberry Pi 5 running Debian trixie to set up:
#   1. rf-agent (relay mode, connects to local relay)
#   2. rf-relay (local relay broker)
#   3. rf-mcp-server (AI agent integration via stdio + HTTP SSE)
#   4. Prometheus metrics endpoint
#   5. Audit HMAC key + SecretStore seal key
#
# Usage:
#   sudo bash setup.sh
#
# Prerequisites:
#   - Raspberry Pi 5, 8GB RAM, aarch64
#   - Debian trixie (bookworm+)
#   - rf-agent, rf-relay, rf-mcp-server binaries in /usr/local/bin/
#   - systemd
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Configuration ────────────────────────────────────────────────────────────
RAVENFABRIC_DIR="/etc/ravenfabric"
LOG_DIR="/var/log/ravenfabric"
BIN_DIR="/usr/local/bin"

# ── Color output ─────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; }

# ── Check prerequisites ──────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
    error "This script must be run as root (sudo)"
    exit 1
fi

for bin in rf-agent rf-relay rf-mcp-server; do
    if [[ ! -x "${BIN_DIR}/${bin}" ]]; then
        error "${BIN_DIR}/${bin} not found. Install binaries first."
        exit 1
    fi
done

# ── Create directories ───────────────────────────────────────────────────────
info "Creating directories..."
mkdir -p "${RAVENFABRIC_DIR}"
mkdir -p "${LOG_DIR}"

# ── Copy configuration files ─────────────────────────────────────────────────
info "Copying configuration files..."
cp "$(dirname "$0")/raven.toml" "${RAVENFABRIC_DIR}/raven.toml"
cp "$(dirname "$0")/policy.yaml" "${RAVENFABRIC_DIR}/policy.yaml"

# ── Generate keys ────────────────────────────────────────────────────────────
info "Generating keys..."

# Agent identity key (auto-generated by rf-agent on first run, but we pre-create)
if [[ ! -f "${RAVENFABRIC_DIR}/agent.key" ]]; then
    "${BIN_DIR}/rf-agent" --key-path "${RAVENFABRIC_DIR}/agent.key" --gen-key-only 2>/dev/null || true
    # If --gen-key-only doesn't exist, rf-agent will generate on first run
    info "Agent key will be auto-generated on first run"
fi

# Audit HMAC key (32 bytes raw)
if [[ ! -f "${RAVENFABRIC_DIR}/audit.key" ]]; then
    dd if=/dev/urandom bs=32 count=1 of="${RAVENFABRIC_DIR}/audit.key" 2>/dev/null
    chmod 600 "${RAVENFABRIC_DIR}/audit.key"
    info "Audit HMAC key generated at ${RAVENFABRIC_DIR}/audit.key"
fi

# Seal key for SecretStore (32 bytes raw)
if [[ ! -f "${RAVENFABRIC_DIR}/seal.key" ]]; then
    dd if=/dev/urandom bs=32 count=1 of="${RAVENFABRIC_DIR}/seal.key" 2>/dev/null
    chmod 600 "${RAVENFABRIC_DIR}/seal.key"
    info "Seal key generated at ${RAVENFABRIC_DIR}/seal.key"
fi

# ── Set permissions ──────────────────────────────────────────────────────────
chmod 755 "${RAVENFABRIC_DIR}"
chmod 644 "${RAVENFABRIC_DIR}/raven.toml"
chmod 644 "${RAVENFABRIC_DIR}/policy.yaml"
chmod 755 "${LOG_DIR}"

# ── Install systemd services ─────────────────────────────────────────────────
info "Installing systemd services..."

# rf-relay service
cp "$(dirname "$0")/../rf-relay.service" /etc/systemd/system/rf-relay.service

# rf-agent service
cp "$(dirname "$0")/../rf-agent.service" /etc/systemd/system/rf-agent.service

# rf-mcp-server service
cp "$(dirname "$0")/../rf-mcp-server.service" /etc/systemd/system/rf-mcp-server.service

systemctl daemon-reload

# ── Enable and start services ────────────────────────────────────────────────
info "Starting services..."

systemctl enable rf-relay
systemctl restart rf-relay
info "rf-relay: $(systemctl is-active rf-relay)"

systemctl enable rf-agent
systemctl restart rf-agent
info "rf-agent: $(systemctl is-active rf-agent)"

systemctl enable rf-mcp-server
systemctl restart rf-mcp-server
info "rf-mcp-server: $(systemctl is-active rf-mcp-server)"

# ── Verify ───────────────────────────────────────────────────────────────────
info ""
info "──────────────────────────────────────────────"
info "RavenFabric rpi5 setup complete!"
info "──────────────────────────────────────────────"
info ""
info "Services:"
info "  rf-relay:      systemctl status rf-relay"
info "  rf-agent:      systemctl status rf-agent"
info "  rf-mcp-server: systemctl status rf-mcp-server"
info ""
info "Logs:"
info "  Agent:         ${LOG_DIR}/audit.jsonl"
info "  MCP Server:    ${LOG_DIR}/mcp-audit.jsonl"
info ""
info "Config:"
info "  ${RAVENFABRIC_DIR}/raven.toml"
info "  ${RAVENFABRIC_DIR}/policy.yaml"
info ""
info "Metrics:"
info "  http://127.0.0.1:9100/metrics"
info ""
info "MCP Server:"
info "  HTTP SSE:      http://127.0.0.1:8080/sse"
info "  stdio:         rf-mcp-server (for AI agent subprocess)"
info ""
info "Next steps:"
info "  1. Verify connectivity: systemctl status rf-agent"
info "  2. Test policy:         rf exec rpi5 uptime"
info "  3. Test audit:          rf audit verify --path ${LOG_DIR}/audit.jsonl --key ${RAVENFABRIC_DIR}/audit.key"
info "  4. Test secrets:        rf secret push --token <TOKEN> --name db_password --value s3cret"
info "──────────────────────────────────────────────"
