{{- if .Values.relay.meetSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ravenfabric.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "ravenfabric.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  meet-secret: {{ .Values.relay.meetSecret | b64enc | quote }}
{{- end }}
