apiVersion: v2
name: ravenfabric
description: RavenFabric — Security-first distributed execution engine
type: application
version: 0.9.0
appVersion: "0.20.0"

home: https://ravenfabric.io
sources:
  - https://github.com/egkristi/RavenFabric

keywords:
  - ravenfabric
  - remote-execution
  - zero-trust
  - mesh-vpn
  - ztna

maintainers:
  - name: Erling Kristiansen
    email: erling@ravenfabric.io
